# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- script: |
  dotnet restore
  dotnet build ./SeedWebApi/SeedWebApi/ --configuration $(buildConfiguration)
  dotnet publish ./SeedWebApi/SeedWebApi/ --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  