# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    -  master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Docker build and Push
  inputs:
    dockerfile: ./SeedWebApi/SeedWebApi/Dockerfile
    command: buildAndPush
    containerRegistry: vramanavarDockerRegistry
    repository: my-project-pipeline-environment
    tags: |
      $(Build.BuildNumber)
      latest