# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    -  master

variables:
  dockerRegistryServiceConnection: 'vramanavarDockerRegistry'
  dockerfilePath: 'SeedWebApi/Dockerfile'
  imageRepository: 'vramanavar/seedwebapi'

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Build and Push SeedWebApi Image - $(Build.SourcesDirectory)
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: 'buildAndPush'
    Dockerfile: $(dockerfilePath)
    tags: |
      latest
- task: KubernetesManifest@0
  displayName: Apply Kubernetes Deployment Manifest
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kubeConnection'
    namespace: 'default'
    manifests: 'kube-deploy.yml'