# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    -  master

variables:
  dockerRegistryServiceConnection: 'vramanavarDockerRegistry'
  dockerfilePath: 'SeedWebApi/Dockerfile'
  imageRepository: 'vramanavar/seedwebapi'

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Build and Push SeedWebApi Image - $(Build.SourcesDirectory)
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: 'buildAndPush'
    Dockerfile: $(dockerfilePath)
    tags: |
      latest
      $(Build.BuildNumber)
- task: replacetokens@3
  inputs:
    rootDirectory: 'SeedWebApi'
    targetFiles: '**/kube-deploy.yml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '<<'
    tokenSuffix: '>>'
    useLegacyPattern: false
    emptyValue: '$(Build.BuildNumber)'
    enableTelemetry: true
- task: KubernetesManifest@0
  displayName: Apply Kubernetes Deployment Manifest
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kubeConnection'
    namespace: 'default'
    manifests: 'SeedWebApi/kube-deploy.yml'