// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersistenceLayer.Repositories;

namespace PersistenceLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PersistenceLayer.Contracts.Models.DatabaseDiamond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Diamond");
                });

            modelBuilder.Entity("PersistenceLayer.Contracts.Models.DatabaseRetailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("DiamondId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DiamondId");

                    b.ToTable("Retailer");
                });

            modelBuilder.Entity("PersistenceLayer.Contracts.Models.DatabaseRetailer", b =>
                {
                    b.HasOne("PersistenceLayer.Contracts.Models.DatabaseDiamond", "Diamond")
                        .WithMany()
                        .HasForeignKey("DiamondId");
                });
#pragma warning restore 612, 618
        }
    }
}
