apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadata-seedwebapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: label-seedwebapi
    spec:
      containers:
        - name: seedwebapi
          image: vramanavar/seedwebapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: label-seedwebapi
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: label-seedwebapi
  type: LoadBalancer