apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadata-seedwebapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: label-seedwebapi
    spec:
      containers:
        - name: seedwebapi
          image: vramanavar/seedwebapi:<<BUILD_NUMBER>>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: label-seedwebapi
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: label-seedwebapi
  type: LoadBalancer